services:
  app:
    build:
      context: ./
      args:
        - ENVIRONMENT=DEV
    image: nsu-inveniordm
    restart: "unless-stopped"
    env_file: .env
    environment:
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://${INVENIO_DB_USER}:${INVENIO_DB_PASSWORD}@db/nsu-inveniordm"
      - "INVENIO_BROKER_URL=amqp://${INVENIO_MQ_USER}:${INVENIO_MQ_PASSWORD}@mq:5672/"
      - "INVENIO_CELERY_BROKER_URL=amqp://${INVENIO_MQ_USER}:${INVENIO_MQ_PASSWORD}@mq:5672/"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
      - "INVENIO_COMMUNITIES_IDENTITIES_CACHE_REDIS_URL=redis://cache:6379/4"
      - "INVENIO_SEARCH_HOSTS=['search:9200']"
      - "INVENIO_PROXYFIX_CONFIG={'x_for': 2}"
    user: ${INVENIO_CONTAINER_UID:-1000}
    group_add:
      - ${INVENIO_CONTAINER_UID:-1000}
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2
  frontend:
    build: ./docker/nginx/
    image: nsu-inveniordm-frontend
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2
  cache:
    image: redis:7
    restart: "unless-stopped"
    read_only: true
    ports:
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:6379:6379"
    volumes:
      - cache-data:/data
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2
  db:
    image: postgres:16.11
    restart: "unless-stopped"
    environment:
      - "POSTGRES_USER=${INVENIO_DB_USER}"
      - "POSTGRES_PASSWORD=${INVENIO_DB_PASSWORD}"
      - "POSTGRES_DB=nsu-inveniordm"
    ports:
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2
  pgadmin:
    image: dpage/pgadmin4:6
    restart: "unless-stopped"
    ports:
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "info@nsu-inveniordm.com"
      PGADMIN_DEFAULT_PASSWORD: "${INVENIO_DB_PASSWORD}"
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2
  # note: RabbitMQ uses the hostname to build the Mnesia data directory path (cf. https://www.rabbitmq.com/docs/configure)
  #       using a randomly generated hostname "forgets" about old queued messages (e.g. celery tasks) with new builds,
  #       and hard-coding the Mnesia path with random hostnames leads to connection issues on startup for old names
  mq:
    image: rabbitmq:3-management
    restart: "unless-stopped"
    hostname: mq
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:15672:15672"
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:5672:5672"
    volumes:
      - mq-data:/var/lib/rabbitmq
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2
  search:
    image: opensearchproject/opensearch:2.19.4
    restart: "unless-stopped"
    environment:
      # settings only for development. DO NOT use in production!
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=guekxe3mvqieke1!%&ieIADE"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    ports:
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:9200:9200"
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:9600:9600"
    volumes:
      - search-data:/usr/share/opensearch/data
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.4
    ports:
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:5601:5601"
    expose:
      - "5601"
    environment:
      # settings only for development. DO NOT use in production!
      - 'OPENSEARCH_HOSTS=["http://search:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2

volumes:
  cache-data:
  db-data:
  mq-data:
  search-data:
