# Example of a full infrastructure stack
#
# Note, this file is not suitable for a production deployment. It is only an
# example of all the infrastructure components needed in a real production
# deployment.
#
# Usage::
#
#   $ docker compose up -f docker-compose.full.yml -d
#
# Following services are included:
# - Frontend: Nginx (exposed ports: 40 and 443)
# - UI application: UWSGI (not exposed)
# - API application: UWSGI (not exposed)
# - Cache: Redis (exposed port: 6379)
# - DB: PostgreSQL (exposed port: 5432)
# - Message queue: RabbitMQ (exposed ports: 5672, 15672)
# - Search platform: (OpenSearch) (exposed ports: 9200, 9600)
# - OpenSearch Dashboard/Kibana (view OS/ES indexes) (exposed ports: 5601)
#
services:
  cache:
    extends:
      file: docker-services.yml
      service: cache
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2
  db:
    extends:
      file: docker-services.yml
      service: db
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2
  mq:
    extends:
      file: docker-services.yml
      service: mq
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2
  search:
    extends:
      file: docker-services.yml
      service: search
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2
  opensearch-dashboards:
    extends:
      file: docker-services.yml
      service: opensearch-dashboards
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2
  pgadmin:
    extends:
      file: docker-services.yml
      service: pgadmin
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2
  # Frontend
  frontend:
    extends:
      file: docker-services.yml
      service: frontend
    volumes:
      - static_data:/var/instance/static
      - ${INVENIO_UPLOADED_DATA_LOCATION:-/data}:/data:ro
    depends_on:
      - web-ui
      - web-api
    ports:
      - "443:443"
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2
  # UI Application
  web-ui:
    extends:
      file: docker-services.yml
      service: app
    command: ["uwsgi /var/instance/uwsgi/uwsgi_ui.ini"]
    image: nsu-inveniordm:latest
    ports:
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:5000:5000"
    volumes:
      - static_data:/var/instance/static
      - ${INVENIO_UPLOADED_DATA_LOCATION:-/data}:${INVENIO_UPLOADED_DATA_LOCATION:-/data}
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2

  # API Rest Application
  web-api:
    extends:
      file: docker-services.yml
      service: app
    command: ["uwsgi /var/instance/uwsgi/uwsgi_rest.ini"]
    image: nsu-inveniordm:latest
    ports:
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:5001:5000"
    volumes:
      - ${INVENIO_UPLOADED_DATA_LOCATION:-/data}:${INVENIO_UPLOADED_DATA_LOCATION:-/data}
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2

  # Worker
  worker:
    extends:
      file: docker-services.yml
      service: app
    command: ["celery -A invenio_app.celery worker --beat --loglevel=INFO"]
    image: nsu-inveniordm:latest
    volumes:
      - ${INVENIO_UPLOADED_DATA_LOCATION:-/data}:${INVENIO_UPLOADED_DATA_LOCATION:-/data}
    depends_on:
      search:
        condition: service_started
      cache:
        condition: service_started
      db:
        condition: service_started
      mq:
        condition: service_started
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2

  # Jobs scheduler
  scheduler:
    extends:
      file: docker-services.yml
      service: app
    command: ["celery -A invenio_app.celery beat --scheduler invenio_jobs.services.scheduler:RunScheduler --loglevel=INFO"]
    image: nsu-inveniordm:latest
    volumes:
      - ${INVENIO_UPLOADED_DATA_LOCATION:-/data}:${INVENIO_UPLOADED_DATA_LOCATION:-/data}
    depends_on:
      mq:
        condition: service_started
      db:
        condition: service_started
    logging:
      driver: json-file
      options:
        max-size: 128m
        max-file: 2

volumes:
  static_data:
  uploaded_data:
  archived_data:
  cache-data:
  db-data:
  mq-data:
  search-data:
  static-data:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1400"
