[project]
name = "nsu_inveniordm_package"
version = "1.0.0"
description = "Add your description here"
requires-python = ">= 3.12"

[project.entry-points."invenio_base.blueprints"]
nsu_inveniordm_views = "nsu_inveniordm.views:create_blueprint"

[project.entry-points."invenio_assets.webpack"]
nsu_inveniordm_theme = "nsu_inveniordm.webpack:theme"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["nsu_inveniordm"]

[tool.isort]
profile = "black"

[tool.pydocstyle]
add_ignore = ["D401", "D403"]

[tool.pytest.ini_options]
addopts = ["--isort", "--pydocstyle", "--doctest-glob=\"*.rst\"", "--doctest-modules", "--cov=nsu_inveniordm", "--cov-report=term-missing", "--exclude-warning-annotations"]
testpaths = "tests nsu_inveniordm"
live_server_scope = "module"
